apiVersion: v1
kind: PersistentVolume
metadata:
  name: html-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/html"  # This directory will be used on the Minikube host
