apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pvc
spec:
  volumeName: html-pv       # 👈 force this PVC to bind to your static PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
