apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: html-pvc
spec:
  storageClassName: ""         # ⬅️ critical line to match static PV with no storage class
  volumeName: html-pv          # ⬅️ explicitly bind to your PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
